name: Python Uppercase Build

on:
  push:
    paths:
      - ".github/workflows/python-uppercase-build.yml"
      - "py-upper/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ['3.11', '3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py-upper/requirements.txt"
          update-pip: "true"

      - name: Run tests
        working-directory: py-upper
        run: pytest -v

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        pyversion: [ '3.11', '3.12']
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE file
        working-directory: py-upper
        run: pyinstaller --onefile uppercase.py

      - name: Rename artifact before upload
        run: mv uppercase.exe uppercase-${{ matrix.pyversion }}.exe
        working-directory: py-upper/dist        

      - name: List files after build
        run: ls -R

      - name: Save artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: "uppercase-exe-${{ matrix.pyversion }}"
          path: "py-upper/dist/uppercase-${{ matrix.pyversion }}.exe"

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: py-upper/dist/uppercase.exe
      #     body: "Binaries of the uppercase program compiled for different Python versions"
      #     tag_name: ${{ github.ref_name }}

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # Allows publishing a release
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: List files
      run: ls -lR

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*
        body: "Binaries of the uppercase program compiled for different Python versions"
        tag_name: ${{ github.ref_name }}
      











      


          
        
